version: "3.8"

services:

  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  backend:
    image: 529646246979.dkr.ecr.ap-southeast-2.amazonaws.com/todo-backend:${TAG}
    container_name: backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db


  nginx:
    image: 529646246979.dkr.ecr.ap-southeast-2.amazonaws.com/todo-nginx:${TAG}
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data: