name: Deploy TodoApp (Develop)
on:
  push:
    branches: ["develop"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup Node
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    # 3. Check structure
    - name: Check project structure
      run: |
        set -e
        echo "Checking folders..."
        test -d backend || (echo "backend missing" && exit 1)
        test -d frontend || (echo "frontend missing" && exit 1)
        echo "Structure OK"

    # 4. Validate files
    - name: Validate required files
      run: |
        set -e
        echo "Checking required files..."
        test -f backend/package.json || (echo "backend/package.json missing" && exit 1)
        test -f nginx.cf || (echo "nginx.cf missing" && exit 1)
        echo "Files OK"

    # 5. Install backend deps
    - name: Install backend
      run: |
        set -e
        cd backend
        npm ci

    # 6. Lint + format check
    - name: Code quality check
      run: |
        set -e
        echo "Running lint..."
        cd backend
        npm run lint

        echo "Running format check..."
        npm run format:check

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ec2-user/todoapp

          git fetch origin
          git reset --hard origin/develop

          # =========================
          # BACKEND
          # =========================
          cd backend
          npm install
          pm2 restart backend || pm2 start index.js --name backend
          cd ..

          # =========================
          # FRONTEND
          # =========================
          cd frontend
          sudo cp index.html /var/www/todoapp/
          cd ..

          # =========================
          # NGINX
          # =========================
          sudo cp nginx.cf /etc/nginx/conf.d/todoapp.conf
          sudo nginx -t
          sudo systemctl reload nginx
